### ISSUE TITLE
ros-industrial robotstudio

### ISSUE THREAD

**Issue by rcj86** [ros-industrial/abb#41] opened 2014-06-07 13:07 UTC
I want move the robot in robotstudio with ros-industrial (virtual machine), but I only can move the robot once.
I use irb2400 abb package.

launch:   roslaunch irb_2400_moveit_config moveit_planning_execution.launch sim:=false robot_ip:=<robot's ip>

Additional info:
Windows 7 64 bits
RobotStudio 5.61
VirtualBox 4.3.12
ROS distro hydro Desktop-Full Install
ROS-I intalled binary package
abb packages -> https://github.com/ros-industrial/abb.git

![ros-i](https://cloud.githubusercontent.com/assets/7824289/3208772/8d81bdf2-ee44-11e3-83e4-b67b4b070223.png)

![fpu](https://cloud.githubusercontent.com/assets/7824289/3208773/914ed280-ee44-11e3-9ad8-5c7ae3fedd6e.png)

![nodes_topic](https://cloud.githubusercontent.com/assets/7824289/3208775/99929e36-ee44-11e3-9062-93c0e40024ce.png)

**Comment by shaun-edwards** [comment] 2014-06-07 23:41
This appears to be bug #42.  The MoveIt execution monitor is sending a stop command to the robot when the first motion takes longer than expected (see [here](http://moveit.ros.org/wiki/Executing_Trajectories_with_MoveIt!#The_Trajectory_Execution_Manager) for more detail).  

The pendant message `STOP received` is indicative of this bug.

There are multiple causes for this:
- The robot is in teach mode (or some other speed limited mode) causing the trajectory to take longer
- The robot joint speed limits are set too high (under the <package>/config directory in the joint_limits.yaml file). This causes MoveIt to think the robot can move faster than it can (the controller doesn't allow this).  Assuming you are using the default joint limits file, this does not appear to be the case.

Other than addressing the causes above, there is a work around (based on the last item in the list  [here](http://moveit.ros.org/wiki/Executing_Trajectories_with_MoveIt!#The_Trajectory_Execution_Manager)  ).
- Set ONE of the following (under the move group node):
  - `~/execution_duration_monitoring` to FALSE (Disables monitoring)
  - `~/allowed_execution_duration_scaling` to a something greater than 1 (i.e. 2) (to increase the time a motion is allowed to exectue)

**Comment by shaun-edwards** [comment] 2014-06-07 23:41
@rcj86, please let me know if this solves the problem.

**Comment by Levi-Armstrong** [comment] 2015-02-02 23:13
@shaun-edwards, This issue was also addressed by PR #62.

**Comment by gavanderhoorn** [comment] 2017-03-09 21:23
I'm closing this because of inactivity.

**Closed as completed by gavanderhoorn** 2017-03-09 21:23 UTC
Labels: duplicate

**Comment by jclinton830** [comment] 2018-12-12 23:11
I am having the same issue. After sending the trajectory data the teach pendant receives a STOP command. On the terminal I get a Controller is taking too long to execute error.

I am using Kinetic-Devel repository in my project and running ros on UBUNTU 16.04.

Any help in this would be appreciated.

**Comment by gavanderhoorn** [comment] 2018-12-13 06:44
Please see [How do I disable execution_duration_monitoring ?](https://answers.ros.org/question/196586). The robot is too slow and MoveIt cancels execution of your trajectory because of that.
